name: Generate Backstop Reference Images
on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base url to generate reference images"
        required: true
        default: 'https://www-dev-ac.cancer.gov'
        type: string
jobs:
  generate_images:
    name: Generate Images
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      ## Install using CI
      - name: Install Dependencies
        run: npm ci