name: Run backstop js visual regression
on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: "Test base url"
        required: true
        type: string
jobs:
  generate_images:
    name: Running backstopjs tests
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      ## Install using CI
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
         ## Now run visual regression 
      - name: Run backstopjs tests
        run: testBaseUrl=${{ inputs.base_url }} npm run backstop:test
      ## Upload failed backstopjs tests
      - uses: actions/upload-artifact@v4
        name: Upload failed tests
        if: failure()
        with:
          name: failed-backstopjs
          path: /home/runner/work/cgov-digital-platform-acceptance-tests/cgov-digital-platform-acceptance-tests/backstop_data/
      ## Upload successful backstopjs tests
      - uses: actions/upload-artifact@v4
        name: Upload successful tests
        with:
          name: success-backstopjs
          path: /home/runner/work/cgov-digital-platform-acceptance-tests/cgov-digital-platform-acceptance-tests/backstop_data/test/**/report.json