name: Run regression (FE and CMS) against ACSF
on: 
  workflow_dispatch:
    inputs:
      base_url:
        base_url:
        description: "CMS base url"
        required: true
        type: string
      front_end_base_url:
        description: "Front end base url"
        required: true
        type: string
jobs:
 front-end-regression:
    name: Running cypress regression tests on ACSF
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'