name: Run Cypress functional regression tests
on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: "Test base url (ode or ac)"
        required: true
        type: string
jobs:
  cypress_regression:
    name: Running cypress regression tests
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
       ## Install using CI
      - name: Install Dependencies
        run: npm ci 
      ### Run Cypress functional tests
      - name: Run tests
        run: CYPRESS_baseUrl=${{ inputs.base_url }} CYPRESS_front_end_base_url=${{ inputs.base_url }} CYPRESS_ocpl_password='${{ secrets.ocpl_password }}' CYPRESS_admin_password='${{ secrets.admin_password }}' npm test
         ## Upload screenshots of failed tests
      - uses: actions/upload-artifact@v2
        name: Upload failed tests
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/cgov-digital-platform-acceptance-tests/cgov-digital-platform-acceptance-tests/cypress/screenshots