name: Run Cypress tests against ACSF/automation-installed
on:
  workflow_dispatch:
    inputs:
      base_url:
        description: ".../automation-installed test base url"
        required: true
        type: string
      akamai_staging:
        description: "Run test on Akamai staging network"
        type: boolean
        default: false
jobs:
  cypress_regression_acsf:
    name: Running cypress regression tests on ACSF
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      ## Override for Akamai staging
      - name: Update hosts file
        if: ${{ inputs.akamai_staging }}
        run: |
          # Retrieve the Akamai staging network IP
          domain=$(echo ${{ inputs.base_url }} | sed -E 's|https?://([^/]+)/.*|\1|')
          subdomain=$(echo ${{ inputs.base_url }} | sed -E 's|https?://([^/]+)\.cancer\.gov.*|\1|')
          ip_address=$(nslookup $subdomain.cancer.gov.edgekey-staging.net | awk '/^Address: / {print $2; exit}')

          # Check if an IP address was found
          if [ -n "$ip_address" ]; then
            echo "$ip_address $domain" | sudo tee -a /etc/hosts
          else
              echo "No IP address found."
              exit 1
          fi
        ## Install using CI
      - name: Install Dependencies
        run: npm ci
        ### Run Cypress functional tests against /automation-installed
      - name: Run tests
        run:
          CYPRESS_baseUrl=${{ inputs.base_url }} CYPRESS_front_end_base_url=${{ inputs.base_url }} npm run cypress:acsf
          ## Upload screenshots of failed tests
      - uses: actions/upload-artifact@v2
        name: Upload failed tests
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/cgov-digital-platform-acceptance-tests/cgov-digital-platform-acceptance-tests/cypress/screenshots
