name: Run ACSF regression (FE and CMS)
on:
  workflow_dispatch:
    inputs:
      base_url:
        base_url:
        description: "CMS base url (without trailing slash)"
        required: true
        type: string
      front_end_base_url:
        description: "Front end base url (without trailing slash)"
        required: true
        type: string
jobs:
  front-end-regression:
    name: Running cypress regression tests on ACSF
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      ## Install using CI
      - name: Install Dependencies
        run: npm ci
      ## Run Cypress functional tests
      - name: Run tests
        run: CYPRESS_baseUrl=${{ inputs.front_end_base_url }}/automation-installed CYPRESS_front_end_base_url=${{ inputs.front_end_base_url }}/automation-installed CYPRESS_ocpl_password='${{ secrets.ocpl_password }}' CYPRESS_admin_password='${{ secrets.admin_password }}' npm run cypress:acsf-parallel
      ## Upload screenshots of failed tests
      - uses: actions/upload-artifact@v2
        name: Upload failed tests
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/cgov-digital-platform-acceptance-tests/cgov-digital-platform-acceptance-tests/cypress/screenshots
      ## Run Cypress CMS tests
      - name: Run CMS tests
        if: always()
        run: CYPRESS_baseUrl=${{ inputs.base_url }} CYPRESS_front_end_base_url=${{ inputs.front_end_base_url }} CYPRESS_admin_password='${{ secrets.admin_password }}' npm run cypress:cms
      ## Upload screenshots of failed tests
      - uses: actions/upload-artifact@v2
        name: Upload failed CMS tests
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/cgov-digital-platform-acceptance-tests/cgov-digital-platform-acceptance-tests/cypress/screenshots
