name: Run Cypress tests against ACSF/automation-installed
on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: ".../automation-installed test base url"
        required: true
        type: string
jobs:
  cypress_regression_acsf:
    name: Running cypress regression tests on ACSF
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
     
    