name: Run Cypress CMS regression tests
on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "CMS url (ode, ac or acsf, NOT acsf/automation-installed)"
        required: true
        type: string
      front_end_base_url:
        description: "Front end url (ode, ac or acsf, NOT acsf/automation-installed)"
        required: true
        type: string
jobs:
  cypress_cms_regression:
    name: Running cypress CMS regression tests
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      ## Install using CI
      - name: Install Dependencies
        run:
          npm ci
          ### Run Cypress CMS tests
      - name: Run tests
        run: CYPRESS_baseUrl=${{ inputs.base_url }} CYPRESS_front_end_base_url=${{ inputs.front_end_base_url }} CYPRESS_admin_password='${{ secrets.admin_password }}' npm run cypress:cms-parallel
        ## Upload screenshots of failed tests
      - uses: actions/upload-artifact@v2
        name: Upload failed tests
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/cgov-digital-platform-acceptance-tests/cgov-digital-platform-acceptance-tests/cypress/screenshots
