name: CGOV Digital Platform Smoke Tests
on:  
  schedule:
    # runs tests every day at 7am
    - cron: '0 12 * * *'
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
      ## Install using CI
      - name: Install Dependencies
        run: npm ci
      - name: Run Smoke Tests
        run: npm run cypress:smoke
        